### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ChristineDewi** [tue-mps/rescience-ijcai2017-230#2]
(KD) D:\PROJECT\rescience-ijcai2017-230>python -m Results.results_coco
loading annotations into memory...
Done (t=6.95s)
creating index...
index created!
loading annotations into memory...
Done (t=3.31s)
creating index...
index created!
COCO test set:                   4000  Images
Loading frequency based consistency matrix
Loading knowledge based consistency matrix
Loading knowledge based consistency matrix
Currently testing:
threshold =  1e-05 bk =  5 lk =  5 epsilon =  0.75 S =  KG-CNet-57-COCO top k =  100
Traceback (most recent call last):
  File "D:\anaconda3\envs\KD\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\KD\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PROJECT\rescience-ijcai2017-230\Results\results_coco.py", line 178, in <module>
    num_classes - 1, topk)
  File "D:\PROJECT\rescience-ijcai2017-230\Utils\testing.py", line 149, in test_function_kg
    boxes_temp = prediction[1][0]['boxes']
IndexError: list index out of range

**Comment by ChristineDewi** [comment]
Can someone help with this code error? thanks

**Comment by hanmo66** [comment]
It should look like this, you can check out this article in CSDN https://blog.csdn.net/qq1198768105/article/details/130102866
# Original
# boxes_temp = prediction[1][0]['boxes']
# labels_temp = prediction[1][0]['labels']
# scores_temp = prediction[1][0]['scores']
# Modified to:
boxes_temp = prediction[0]['boxes']
labels_temp = prediction[0]['labels']
scores_temp = prediction[0]['scores']
